<?php
/**
 * LogicSpot_Imageload
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GNU General Public License v3.0
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.gnu.org/licenses/gpl-3.0.txt
 *
 * @category    LogicSpot
 * @package     LogicSpot_Imageload
 * @copyright   Copyright (c) 2015 LogicSpot (http://www.logicspot.com)
 * @license     http://www.gnu.org/licenses/gpl-3.0.txt GNU General Public License v3.0
 */
?>
<script type="text/javascript">
//<![CDATA[
    var BASE_URL = '<?php echo Mage::getBaseUrl(); ?>';
    var IMAGELOAD_ENABLE = <?php var_export(Mage::helper('imageload')->isModuleEnabled()); ?>;
//]]>
</script>
